name: Cakebrew

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
      submodules: recursive
    - name: Build
      run: xcodebuild -workspace Cakebrew.xcworkspace/ -scheme Cakebrew
    - name: Run tests
      run: xcodebuild -workspace Cakebrew.xcworkspace/ -scheme Cakebrew test
